# Generated by Django 5.2.8 on 2025-11-06 15:18

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')])),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('responsavel_tecnico', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator(message='Informe um email válido.')])),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar em formato válido (ex: +55 11 91234-5678)', regex='^\\+?\\d{0,3}?[ -]?\\(?\\d{2,3}\\)?[ -]?\\d{4,5}[ -]?\\d{4}$')])),
                ('numero_maximo_maquinas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número máximo de máquinas')),
                ('numero_pontos_infraestrutura', models.PositiveIntegerField(default=0, verbose_name='Número de pontos de infraestrutura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
