# Generated by Django 5.2.8 on 2025-11-06 17:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clinics_delete_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('FISICO-QUIMICO', 'Físico-Químico'), ('MICROBIOLOGICO', 'Microbiológico')], max_length=20)),
                ('unidade', models.CharField(choices=[('μg/ml', 'μg/ml'), ('ng/ml', 'ng/ml'), ('mg/L', 'mg/L'), ('%', '%')], max_length=10)),
                ('periodicidade', models.CharField(choices=[('MENSAL', 'Mensal'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='SEMESTRAL', max_length=15)),
                ('limite_minimo', models.FloatField(blank=True, null=True)),
                ('limite_maximo', models.FloatField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('INFRA', 'Infraestrutura'), ('MAQUINA', 'Máquina')], max_length=10)),
                ('nome', models.CharField(max_length=150)),
                ('analises_de_agua', models.JSONField(blank=True, default=dict)),
                ('clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='core.clinics')),
            ],
        ),
        migrations.CreateModel(
            name='WaterAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], max_length=15)),
                ('data_da_coleta', models.DateField(default=django.utils.timezone.now)),
                ('data_da_proxima_coleta', models.DateField(blank=True, null=True)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_agua', to='core.point')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='core.waterparameter')),
            ],
        ),
    ]
