# Generated by Django 5.2.8 on 2026-02-06 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_waterparameter_point_wateranalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinics',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')]),
        ),
    ]
