# Generated by Django 5.2.8 on 2026-02-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_clinics_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterparameter',
            name='categoria',
            field=models.CharField(choices=[('FISICO-QUIMICO', 'Físico-Químico'), ('MICROBIOLOGICO', 'Microbiológico'), ('ENDOTOXINA', 'Endotoxina'), ('CONDUTIVIDADE', 'Condutividade'), ('PH', 'pH')], max_length=20),
        ),
        migrations.AlterField(
            model_name='waterparameter',
            name='unidade',
            field=models.CharField(choices=[('μg/ml', 'μg/ml'), ('ng/ml', 'ng/ml'), ('EU/ml', 'EU/ml'), ('UFC/mL', 'UFC/mL'), ('mg/L', 'mg/L'), ('µS/cm', 'µS/cm'), ('%', '%')], max_length=10),
        ),
    ]
